version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "update-deps"

    default_reviewers:
      - "ayfri"
    default_labels:
      - "dependencies"
