name: Continuous Integration

on: [pull_request, push, workflow_dispatch]

permissions:
  workflows: write-all

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.4
              with:
                node-version: '15'

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: lint
              uses: stefanoeb/eslint-action@1.0.2
              with:
                  files: src

            - name: Prettify code
              uses: creyD/prettier_action@v3.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  prettier_options: . --write
