name: Continuous Integration
on:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 1'
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.4

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: lint
              run: yarn lint

            - name: Prettify
              run: yarn prettier
