name: Continuous Integration
on:
    pull_request:
    workflow_dispatch:
    schedule:
        -   cron: '0 0 * * 1'
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Lint
              uses: ./.github/workflows/lint
            - name: Prettier
              uses: ./.github/workflows/prettier,
            - name: CodeQL Analyze
              uses: ./.github/workflows/codeql-analysis
