name: Lint
on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.4

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run ESLint
              run: npm run lint
